### ISSUE TITLE
[useSpring] `cleanup` is not a function

### ISSUE THREAD

**Issue by khang-nd** [motiondivision/motion-vue#21]
Hello, I'm getting the above error when unmounting the components that use spring animation (e.g when changing route). Likely a version mismatch with framer-motion package?

Line affected:
https://github.com/unovue/motion-vue/blob/910da65fa213dd1df8d4fdc116f3a49565b13b3e/packages/motion/src/value/use-spring.ts#L61

Here's a simple repro for your reference: https://stackblitz.com/edit/motion-vue-repro.

**Comment by rick-hup** [comment]
@khang-nd  this will be fixed in next version

**Comment by rick-hup** [comment]
fixed it in 0.5.1

**Comment by khang-nd** [comment]
Thank you, that was quick ⚡
