### ISSUE TITLE
Initial prop in AnimatePresence disables animations on all renders instead of only first render

### ISSUE THREAD

**Issue by alshchetinin** [motiondivision/motion-vue#23]
## Description
According to the documentation (https://motion.dev/docs/react-animate-presence#initial), the `initial` prop should only disable initial animations on children that are present during the first render of the component.

However, the current behavior disables animations not only on the first render but on all subsequent renders as well.

## Expected Behavior
- `:initial="false"` should only disable animations during the first render of the component
- Subsequent renders should animate normally

## Actual Behavior  
- `:initial="false"` disables animations on both first render and all subsequent renders
- No animations are played on any render

## Steps to Reproduce
1. Create an AnimatePresence component with `:initial="false"`
2. Add animated children components
3. Observe that animations are disabled not only on first render but also when children update/change later

**Comment by rick-hup** [comment]
hi @alshchetinin! can you Provide a CodeSandbox reproduction of this?

**Comment by alshchetinin** [comment]
Hi! Here's a [CodeSandbox reproduction demonstrating the issue](https://codesandbox.io/p/devbox/fragrant-rain-3x9z9l?file=%2Fapp.vue)

**Comment by rick-hup** [comment]
hi @alshchetinin , in v0.6.0 fixed it
