### ISSUE TITLE
bug: animation not smooth 

### ISSUE THREAD

**Issue by reslear** [motiondivision/motion-vue#24]
| vue | react |
|---|---|
| <video src="https://github.com/user-attachments/assets/3ca4983a-97c1-4b41-a50b-7c03db6ccbdb" /> | <video src="https://github.com/user-attachments/assets/73fb1858-bf66-4355-92d2-b40535daac1f" /> |

vue playground: 
https://stackblitz.com/edit/vitejs-vite-jeqjxutb?file=src%2Fstyle.css

react playground: 
https://stackblitz.com/edit/vitejs-vite-4t4wdvey?file=package.json

i don't know why animation not smooth, 
also i have trouble with AnimatePresence in react need add `if` for child component, but on vue `v-if` for root AnimatePresence

**Comment by rick-hup** [comment]
hey! @reslear , Unlike React, Vue child components don't re-trigger their lifecycle hooks when their parent component updates, so we need to implement a suitable solution for this behavior.

**Comment by rick-hup** [comment]
[9bef2e7a-125d-4007-85a4-883050eb3f1d.webm](https://github.com/user-attachments/assets/2eb71304-297d-4a97-b035-58dcbe42a73c)
 
@reslear  found a solution to fix this issue... but still needs some testing. Will probably release a version next few days to fix it

**Comment by reslear** [comment]
hi @rick-hup Wow, that's really cool, ready to test..)

**Comment by rick-hup** [comment]
https://stackblitz.com/edit/vitejs-vite-e19yd3ez?file=package.json,src%2FApp.vue,package-lock.json

**Comment by rick-hup** [comment]
@reslear  in v0.6.0,you can use LayoutGroup component to froce child layout change 
https://motion.unovue.com/components/layout-group#default-the-default-slot-receives-forcerender-function

**Comment by reslear** [comment]
@rick-hup that's really, really great work. Congratulations.
